const ANALYSIS_LONG_EDGE = 256;
const GUIDE_MAX_CHANGES_BASE = 1000;
const GUIDE_MAX_CHANGES_FRAME_COUNT = 10000;
const GUIDE_BOX_EXPAND_RATIO = 1.5;
const GUIDE_BOX_EXPAND_PIXELS = 8;
const GUIDE_DIFF_THRESHOLD = 24;
const GUIDE_BOX_LINE_THICKNESS = 3;
const VISUAL_GUIDE_BOX_COLOR = "red";

exports.ANALYSIS_LONG_EDGE = ANALYSIS_LONG_EDGE;
exports.GUIDE_MAX_CHANGES_BASE = GUIDE_MAX_CHANGES_BASE;
exports.GUIDE_MAX_CHANGES_FRAME_COUNT = GUIDE_MAX_CHANGES_FRAME_COUNT;
exports.GUIDE_BOX_EXPAND_RATIO = GUIDE_BOX_EXPAND_RATIO;
exports.GUIDE_BOX_EXPAND_PIXELS = GUIDE_BOX_EXPAND_PIXELS;
exports.GUIDE_DIFF_THRESHOLD = GUIDE_DIFF_THRESHOLD;
exports.GUIDE_BOX_LINE_THICKNESS = GUIDE_BOX_LINE_THICKNESS;
exports.VISUAL_GUIDE_BOX_COLOR = VISUAL_GUIDE_BOX_COLOR;
